# Generated by Django 6.0.3 on 2026-04-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_classroom_alter_teacher_off_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='off_day',
            field=models.CharField(choices=[('Pazartesi', 'pazartesi'), ('Salı', 'sali'), ('Çarşamba', 'carsamba'), ('Perşembe', 'persembe'), ('Cuma', 'cuma')], max_length=100),
        ),
    ]
