# Generated by Django 5.2.8 on 2026-04-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_scheduleentry_courserequirement_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='course',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='room',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='teacher',
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='schedule',
            field=models.JSONField(default=list),
        ),
    ]
