# Generated by Django 5.2.8 on 2026-04-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_teacher_off_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='off_day',
            field=models.CharField(choices=[('Pazartesi', 'Pazartesi'), ('Sali', 'Salı'), ('Carsamba', 'Çarşamba'), ('Persembe', 'Perşembe'), ('Cuma', 'Cuma')], max_length=100),
        ),
    ]
