# Generated by Django 6.0.3 on 2026-04-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_off_day_ascii_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='off_day',
            field=models.CharField(choices=[('1', 'Pazartesi'), ('2', 'Salı'), ('3', 'Çarşamba'), ('4', 'Perşembe'), ('5', 'Cuma')], max_length=100),
        ),
    ]
