# Generated by Django 5.2.8 on 2026-04-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_teacher_off_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='off_day',
            field=models.CharField(choices=[('1', 'Pazartesi'), ('2', 'Salı'), ('3', 'Çarşamba'), ('4', 'Perşembe'), ('5', 'Cuma')], max_length=100, null=True),
        ),
    ]
